kind = "web"
previewPath = "/"
title = "Corrida do Retorno da Praia"
version = "1.0.0"
id = "artifacts/corrida-retorno-praia"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25432

[services.development]
run = "pnpm --filter @workspace/corrida-retorno-praia run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/corrida-retorno-praia", "run", "build" ]
publicDir = "artifacts/corrida-retorno-praia/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25432"
BASE_PATH = "/"
